### ISSUE TITLE
After update post, the post rating is reset

### ISSUE THREAD

**Issue by conlamochila** [lesterchan/wp-postratings#107]
Hello, 
When we update a post, the postrate starts image and count is reset. 0 votes
BUT In postrating manager page (/admin.php?page=wp-postratings%2Fpostratings-manager.php) we can see the votes. The votes are not deleted, but the counter on the post page is reset.

Please, could you test it?

Regards

**Comment by lesterchan** [comment]
That is a side effect unfortunately because WordPress updates custom post meta. My advice is ask users not to hang around the edit page for too long. You want to edit the page then click the link.

**Comment by conlamochila** [comment]
Hello Lesterchan.
I'm testing this issue and if you spend only 5 seconds to edit the post and save, the rating is reset too. Then how we edit our posts and maintain ratings? 
I see that postmeta table reset the rating values (users, score, average)

Regards

**Comment by lesterchan** [comment]
Unfortunately there is no way. If within the 5 seconds you get any ratings it will be lost. The ratings logs will be there, but I have no time to build a feature to reconsolidation logs to the aggregated ratings.

**Comment by conlamochila** [comment]
Just an appreciation. The rating is lost even if there are no ratings in that time. Just editing and saving rating values are reset to 0,0,0

Thanks for your time Lesterchan, i know you do you do this in an altruistic way

**Comment by lesterchan** [comment]
Weird that should not be the case. Maybe you are using a conflicting plugin or theme that cause it.

If you have already ratings, editing the post will not lose the existing ratings. That just doesn't make sense.

That is why I am guessing some themes or plugins you are using are messing with the saving of the post.

If you can reproduce this error with a fresh install or WP and this plugin, let me know.

**Comment by conlamochila** [comment]
Ok, thanks again.

**Comment by conlamochila** [comment]
lesterchan, in a fresh install with WP 4.8.1 and default templates work. With my template, fail ;)
I think the template is not fully compatible with WP 4.8.1. When we use previous versions of WP the plugin with the template works fine. Now, the same template and a new version of WP... crash!!! 

Thanks for your help

**Comment by conlamochila** [comment]
Hello Lester, this issue is caused by the One_Clic_Install. The file radium-importer.php has this code
` public function check_previous_meta( $continue, $post_id, $meta_key, $meta_value, $unique ) {

			$old_value = get_metadata( 'post', $post_id, $meta_key );

			if ( count( $old_value ) == 1 ) {

				if ( $old_value[0] === $meta_value ) {

					return false;

				} elseif ( $old_value[0] !== $meta_value ) {

					update_post_meta( $post_id, $meta_key, $meta_value );
																  
					return false;

				}

			}

    	}`

If you comment 
//update_post_meta( $post_id, $meta_key, $meta_value );
//return false;

The pluggin works fine again.

You can see the complete file here
https://github.com/FrankM1/radium-one-click-demo-install/blob/master/importer/radium-importer.php

Previos versions of this file had commented this lines and works

Regards
Anselmo
