### ISSUE TITLE
Multiple Structure Error

### ISSUE THREAD

**Issue by Milor123** [lesterchan/wp-postratings#109]
Hi guys, when I enable the snippet in my post then I get this errors:
I would like how disable some rich.
I have knowledge of develop.. Could use some one filter for add the data? 

![image](https://user-images.githubusercontent.com/14153649/32089864-1fa8696e-bab2-11e7-96eb-5877ebdbc886.png)

![image](https://user-images.githubusercontent.com/14153649/32089923-65ba019c-bab2-11e7-9105-32ef4f91a8a5.png)

It if i think that could be a bug of the wp-postratings.:
![image](https://user-images.githubusercontent.com/14153649/32089943-7ca5b5ea-bab2-11e7-8f47-6145c385c6ad.png)

**Comment by lesterchan** [comment]
Duplicate https://wordpress.org/support/topic/multiple-structured-data-error/
