### ISSUE TITLE
Use text instead of images 

### ISSUE THREAD

**Issue by DavidVII** [lesterchan/wp-postratings#11]
I'd love it if I could use text instead of an image. This way I can style it and with css and not have rely on an image for the button text.

I'd love to create a set of buttons with css. Something like this:

```
<div class="rating btn">1 Star</div>
<div class="rating btn">2 Star</div>
<div class="rating btn">3 Star</div>
```

Then I could style it any way I want.

Thoughts?

**Comment by StaggerLeee** [comment]
Why not load WP Dashicons at frontend with plugin and use them ? They have almost evrything needed. No multiple HTTP requests. Unlimited styling options with simple CSS.
