### ISSUE TITLE
Dynamically updating aggregateRating data for JSON structured data

### ISSUE THREAD

**Issue by capitalcocktails** [lesterchan/wp-postratings#114]
Love the plug-in.  I'm trying to get a JSON-LD script to dynamically update the aggregateRating property (for ratingValue and reviewCount) with the star ratings on the page.  Is there a way to do this easily?  Here is the snippet from the script, which is in the body of the post (and which did not work - I don't know much about php and tried to figure out how to do it by searching online):

<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "Recipe",
  "aggregateRating": { 
    "@type": "AggregateRating", 
    "ratingValue": <?php echo json_encode($post_ratings_average); ?>, 
    "reviewCount": <?php echo json_encode($post_ratings_users); ?> 

Thanks in advance.

**Comment by lesterchan** [comment]
Use `<?php echo get_post_meta( get_the_ID(), 'ratings_users', true ); ?>` for reviewCount and `<?php echo get_post_meta( get_the_ID(), 'ratings_average', true ); ?>` for ratingValue

**Comment by capitalcocktails** [comment]
This worked perfectly, thanks so much.
