### ISSUE TITLE
How to properly replace the pictures of stars with their own?

### ISSUE THREAD

**Issue by seredniy** [lesterchan/wp-postratings#123]
In the case of updating the plugin, my changes are not erased. Thank you!

**Comment by seredniy** [comment]
any body home?)

**Comment by lesterchan** [comment]
You might want to refer here https://wordpress.org/support/topic/custom-stars-1/.

It is not possible to prevent it from being erased as this plugin was not designed to have custom stars (due to a poor oversight on my end)

**Comment by seredniy** [comment]
Thank you for answer!
