### ISSUE TITLE
Undefined Variable: Thumbnail ...

### ISSUE THREAD

**Issue by wichaksono** [lesterchan/wp-postratings#126]
hello, i create new custom post type and I get error like this : 
![image](https://user-images.githubusercontent.com/11472981/40963189-f1424a94-68d1-11e8-95d7-3524d0bb1562.png)

what can i do ?

**Comment by lesterchan** [comment]
Use the master branch https://github.com/lesterchan/wp-postratings/archive/master.zip, it is already fixed in https://github.com/lesterchan/wp-postratings/commit/28b81b349e04da9af5a69b40f8a3f9fb847df969
