### ISSUE TITLE
Schema validation problem

### ISSUE THREAD

**Issue by majestica** [lesterchan/wp-postratings#129]
Hi, can you help solve this error
https://search.google.com/structured-data/testing-tool/u/0/?hl=ru#url=https%3A%2F%2Fe-groshi.com%2Fru%2Fkak-tehnologyya-bankid-rabotaet-v-fynansovoj-kompanyy-ye-groshi%2F
?

**Comment by lesterchan** [comment]
Read the FAQ https://github.com/lesterchan/wp-postratings `How To Add Your Site Logo For Google Rich Snippets`
