### ISSUE TITLE
One user vote for all

### ISSUE THREAD

**Issue by Alconis** [lesterchan/wp-postratings#133]
HI Lester,

Since the update to 1.86 and the move to hashed IP, I now have a serious issue on my website (https://www.birdsdessines.fr) : in fact, as soon as one user votes for a post, the other users are marked as if they had voted for it as well.

I've configured it so that guest and logged users can vote. It's been working fine for years until this update. I've emptied the votes logs and asked my users to empty their cookies as I'm using both technique for logging. To no avail.

In the votes log, the hashed IPs are different but the host IP is the same. I'm wondering if it can come from this or if it is normal.

The votes on my site is the core of engagement of the community and they are pretty angry lately because of this bug making them "vote" for people they don't want to.

Thanks in advance for the quick help!!

**Comment by lesterchan** [comment]
Hmm, how can the hash be different if the IP is the same? The hash is based on the IP https://github.com/lesterchan/wp-postratings/blob/master/wp-postratings.php#L402

You can remove this https://github.com/lesterchan/wp-postratings/commit/d7dbb605ee428929f8364426011f4435e718a7a7 so that it checks on the hash instead of the IP.

**Comment by Alconis** [comment]
Indeed, I found that weird, hence my pointing. See for yourself:
<img width="1254" alt="screenshot 2018-12-27 at 10 48 04" src="https://user-images.githubusercontent.com/953316/50475417-021a5c00-09c5-11e9-82b5-8ef63a074743.png">

**Comment by lesterchan** [comment]
<img width="1253" alt="screenshot 2018-12-27 at 8 51 11 pm" src="https://user-images.githubusercontent.com/355829/50480814-2ef85e80-0a19-11e9-8e4a-d0958d8b5fc0.png">
Weird, I rated in two different posts and the hash is the same. 

Note that the host is not the IP and it doesn't hash on that.

Regardless, I added a filter `wp_postratings_ipaddress`.

So you can do something like `add_filter( 'wp_postratings_ipaddress', 'get_ipaddress' );` to restore the default behaviour. For now, just overwrite the https://raw.githubusercontent.com/lesterchan/wp-postratings/master/wp-postratings.php file

**Comment by Alconis** [comment]
Using your new file, I've leveraged the filters like this:

```php
add_filter( 'wp_postratings_ipaddress', 'birds_wp_postratings_ipaddress', 10, 3 );
function birds_wp_postratings_ipaddress( $hashed_ip_adress ) {

// Override with latest functional version of WP Post Ratings plugin
// https://github.com/lesterchan/wp-postratings/commit/818abe4ec964070034eebc61eb328fd826a03b72#diff-52f82710ce0fde4d4863f202985baa49L387

  if (empty($_SERVER["HTTP_X_FORWARDED_FOR"])) {
      $ip_address = $_SERVER["REMOTE_ADDR"];
  } else {
      $ip_address = $_SERVER["HTTP_X_FORWARDED_FOR"];
  }
  if(strpos($ip_address, ',') !== false) {
      $ip_address = explode(',', $ip_address);
      $ip_address = $ip_address[0];
  }
  return esc_attr($ip_address);
}

add_filter( 'wp_postratings_hostname', 'birds_wp_postratings_hostname', 10, 3 );
function birds_wp_postratings_hostname( $hostname ) {
  return $hostname;
}

```

**Comment by Alconis** [comment]
I think I've found the issue. My real client ip address is in the 'REMOTE_ADDR' HTTPheader. But since it's at the end of the list of checked headers and since there is a wrong IP given in HTTP_X_FORWARDED_FOR (the one of my CDN/Load Balancer/SSL Gateway I guess), it's this front-end IP that is stored and checked against and not the real client one.

```php
add_filter( 'wp_postratings_ipaddress', 'birds_wp_postratings_ipaddress', 10, 3 );
function birds_wp_postratings_ipaddress( $ip_adress ) {

  if(strpos($_SERVER["REMOTE_ADDR"], ',') !== false) {
      $ip_address = explode(',', $ip_address);
      $ip_address = $ip_address[0];
  }
  return esc_attr($ip_address);
}
```

**Comment by lesterchan** [comment]
@Alconis you can just change it to `add_filter( 'wp_postratings_ipaddress', 'birds_wp_postratings_ipaddress', 10 );`

There is only one argument in the function.
