### ISSUE TITLE
No postratings at pages

### ISSUE THREAD

**Issue by tinykanters** [lesterchan/wp-postratings#139]
Hi,
I really love your rating plugin!
I have a question: The ratings work fine at all posts but are **invisible at the PAGES???** Though I see the rating-column in the page-list. Is there something that I do wrong?
If I add the rating by hand on a page with the shortcode and ID is works fine.
Can you please help me?
My website is: personaldevelopmentXL.com

Kind regards,
Tiny

**Comment by lesterchan** [comment]
You might need to contact your theme author. I am not sure how your theme is designed. You have to add the same PHP code to your pages template as well.

**Comment by tinykanters** [comment]
Thank you so much for your comment, I followed your advice. It works fine now :)
Kind regards 
Tiny
