### ISSUE TITLE
Get only rating %

### ISSUE THREAD

**Issue by AntonGrekov** [lesterchan/wp-postratings#151]
Is there a php-way to get only number of rating issued by users to post ID ?

I just want the raw number, nothing else. Something like:
````php
<?php echo the_ratings( $post_id, array('only_number' => true) ) . '%'; ?>
````
and as a result i get **95%** of that $post_id.
Thank you

**Comment by lesterchan** [comment]
`<?php echo get_post_meta( $post_id, 'ratings_average', true ); ?>`

**Comment by AntonGrekov** [comment]
Thank you !
