### ISSUE TITLE
Problem with Elementor

### ISSUE THREAD

**Issue by mushlih-almubarak** [lesterchan/wp-postratings#152]
I combined your plugins and elementor and the [Advance Post Query](https://wordpress.org/plugins/advanced-post-queries/) plugin to display posts in the "post" widget on elementor pro based on a specific query, and I used with your plugin's "views" query to display the most popular posts in the "post" widget.
But why are only posts displayed under 10 views?

**Comment by bule10a** [comment]
Hello, 
I face the same issue. Have you maybe fixed it and can share your solution?
Thank you!
