### ISSUE TITLE
Wp-postrating not working after Ajax load

### ISSUE THREAD

**Issue by mkkmail** [lesterchan/wp-postratings#37]
i use jquery 1.11 and this code to ajax load wordpress post content in sidebar . everything is good but jquery functions of wp-postrating not work and the rating system in post content not work.

 ajaxify code to load post content:

    jQuery(document).ready(function($){
    $.ajaxSetup({cache:false});
    $(".post-link").click(function(){
    var post_link = $(this).attr("href")+' #content';
    $("#single-post-container").html("loading ...");
    $("#single-post-container").load(post_link);
    return false;
    });
    });
How can i use .ajaxcomplete() function to load it after ajax load post or any idea you can advice me.

 best regards.

**Comment by lesterchan** [comment]
It doesn't work with the plugin because the plugin uses onmouseover HTML attribute instead of using JS. So unlikely you can do what you are doing.

**Comment by mkkmail** [comment]
i used this code and wp-postrating work well ;)


	jQuery(document).ready(function($){
		$.ajaxSetup({cache:false});
		$(document).on('click', ".post-link", function () {
			$( ".sidebar" ).toggleClass( "sidebar-slide" );
			$( ".content-wrap" ).toggleClass( "content-slide" );
            var post_link = $(this).attr("href")+' #content';
            $("#single-post-container").html("<div class='loader'></div><span class='tload'>بارگذاری ...</span>");
			$("#single-post-container").load($(this).attr("href")+' #content', function(response, status, xhr) { // complete callback

					// create a empty div
					var div = document.createElement('div');
					// fill div with response
					div.innerHTML = response;
					// take correct part of the response
					var ref = $($(div).find('#content').html());
					// filter response for script tags
					ref.filter('script').each(function () {
						// execute the scripts
						$.globalEval(this.text || this.textContent || this.innerHTML || '');
					});
				
			});

        return false;
        });
    });

**Comment by lesterchan** [comment]
#TIL that there is something called globalEval!
