### ISSUE TITLE
Ratings templates by custom post type or taxonomy

### ISSUE THREAD

**Issue by raulillana** [lesterchan/wp-postratings#39]
Yo @lesterchan! :wave:

It would be nice to be able to set up different themes/templates (display options) for custom post types or custom taxonomies. Something like this.

```<?php if( function_exists('wp_ratings') ) wp_ratings($template = 'template-name') ?>```

Best! :+1:

**Comment by lesterchan** [comment]
That is a bit impossible with the current design of the plugin because the plugin is designed to use the global template option.

**Comment by raulillana** [comment]
@lesterchan so if my posts and my CPT books should show a different ratings UI, what should i do?

**Comment by lesterchan** [comment]
You cannot do anything because that is not possible.

**Comment by raulillana** [comment]
Actually since CPT are part of the core, you should. But ok.

Sorry for the inconvenience.

**Comment by lesterchan** [comment]
Yeap CPT is in the core but it has nothing to do with multiple templates for this plugin. Feel free to fork this plugin and modify it to suite your needs.
