### ISSUE TITLE
Use filters to change 'RATINGS_IMG_EXT'

### ISSUE THREAD

**Issue by ramiy** [lesterchan/wp-postratings#44]
Currently, to change image extension from GIF to PNG we need to edit the plugin file and change the RATINGS_IMG_EXT value from GIF to PNG. It's a bad practice, on each plugin upgrade our changes are deleted.

Let's make it easier to change the file type using wordpress filters, without changing the plugin. The filter can be fired from the theme function.php file, and the plugin upgrade won't affect the filter.

Theme authors will use code like this:

```
function custom_rating_img_ext() {
	return 'png';
}
add_filter( 'rating_img_ext', 'custom_rating_img_ext' );
```

**Comment by lesterchan** [comment]
Thanks for this!

**Comment by ramiy** [comment]
Thank you for the plugin.
:-)


Rami Y.
GenerateWP.com
