### ISSUE TITLE
Touch terrible UX

### ISSUE THREAD

**Issue by bluantinoo** [lesterchan/wp-postratings#54]
On mobile phones or tablets is quite difficult to cast a vote.  As there's no hover state, you understand what you've voted only after you did it.

Possibile quick solution:
1) pretty larger stars
2) confirm vote before definitive submit

**Comment by lesterchan** [comment]
This plugin is dated. It is not possible to fix those without a rewrite. But the problem is I have no time to do a rewrite. So feel free to submit a PR to help =)

**Comment by bluantinoo** [comment]
Hi Lester,
I'm not a good coder as you are, but I've tried to figure out a workaround. It's not perfect, as on ouch devices the hover state on stars remains active and if someone tells "no" to confirm the second time he try to vote he has to tap twice on stars. But at least like this on touch you can be sure of the vote you're casting.

feel free to improve or trash this idea:

I edited postratings-js.js

1) renamed the function rate_post() (process post ratings) to confirm_rate_post()
2) created a new function rate_post() that ask for confirmation (no alert, it's a dinamically box that you can style via css) and if confirm is given calls confirm_rate_post().

here it is my clumsy function

// Confirmation Dialog
function rate_post(){

	jQuery('#confirm-post-ratings-'+post_id).remove();
	
	var confirm_dialog = '<div id="confirm-post-ratings-'+post_id+'" class="confirm-rating">' + 
							'<p>Confirm your rating of ' + post_rating + ' on ' + ratingsL10n.max + '?</p>' +
							'<a class="yesconfirm">YES</a> ' + 
							'<a class="noconfirm">NO</a>' +
						  '</div>';
	 
	jQuery(confirm_dialog).appendTo('#post-ratings-'+post_id);
	       
	jQuery('#confirm-post-ratings-'+post_id).on('click touchstart', 'a', function() {
		if (jQuery(this).hasClass('yesconfirm')){
			jQuery('#confirm-post-ratings-'+post_id).remove();
			confirm_rate_post();  // here the call to previous rate_post() function now renamed
		} else {
			jQuery('#confirm-post-ratings-'+post_id).remove();
			jQuery(this).stop( true, true );
		}
		
	});
	
}
