### ISSUE TITLE
Add %POST_THUMBNAIL% Template Variable

### ISSUE THREAD

**Issue by lesterchan** [lesterchan/wp-postratings#55]
```
$thumbnail = get_the_post_thumbnail( $post->ID, 'thumbnail', true );
$temp = str_replace( '%POST_THUMBNAIL%', $thumbnail, $temp );
```

**Comment by arafatx** [comment]
any news on this? where to add this line ?

**Comment by ramiy** [comment]
It can be a very good enhancement to the current plugin!

**Comment by Demontager** [comment]
Waiting too, great feature.

**Comment by scriptgeni** [comment]
When can we expect this or where can we add 

> $thumbnail = get_the_post_thumbnail( $post->ID, 'thumbnail', true );
$temp = str_replace( '%POST_THUMBNAIL%', $thumbnail, $temp );

**Comment by lesterchan** [comment]
I have added it to the dev version, you can try it here https://github.com/lesterchan/wp-postratings/archive/master.zip
