### ISSUE TITLE
Apply only to selected post types

### ISSUE THREAD

**Issue by ramiy** [lesterchan/wp-postratings#57]
When I have multiple Post Types, I see the rating columns in each and every one of them.

We need to be able to choose which post types will have ratings and which are not.

**Comment by lesterchan** [comment]
I am hesitant to add in another options. I got more request making it show for every post type then the other way.

**Comment by ramiy** [comment]
I usually develop sites with multiple CPT. When I use this plugin, it added the rating feature to all the CPT's. This is not the expected behavior from my point of view.

We can fix this in two ways:

1. Create a settings page where the user select the CPT's, and apply the ratings only to those CPT's (for backward-compatibility all the CPT's will be checked by default).

2. Or, to apply the ratings to all CTP's (like the current plugin behaves), but to allow developers to remove some CPT's using a filter/action.

**Comment by lesterchan** [comment]
I like the second way rather than adding in another option! Feel free to send a pull request!
