### ISSUE TITLE
Add an option to vote again after specified time

### ISSUE THREAD

**Issue by vasikgreif** [lesterchan/wp-postratings#65]
For my setup I adjusted the code so users can vote again after one day. I had to do just two changes:

`$rate_cookie = setcookie("rated_".$post_id, $ratings_value[$rate-1], strtotime('tomorrow'), apply_filters('wp_postratings_cookiepath', SITECOOKIEPATH));`

and 

`$get_rated = $wpdb->get_var( $wpdb->prepare( "SELECT rating_ip FROM {$wpdb->ratings} WHERE rating_postid = %d AND rating_ip = %s AND DATE(NOW() - INTERVAL 1 DAY) >= rating_timestamp", $post_id, get_ipaddress() ) );`

I'd suggest to at least add filters for these calls, so developers can adjust whatever they need, or even better, add an option to the frontend to let users choose the period after which the users can vote again...

**Comment by lesterchan** [comment]
Why don't you submit a PR with the filter instead?

**Comment by vasikgreif** [comment]
Wanted to discuss this first with you - as said, I think it might be even better to make this a new feature with a new swetting in admin...

**Comment by lesterchan** [comment]
As mentioned I don't want to keep adding options. I would opt for filter and actions anytime.

You might want to read this https://wordpress.org/about/philosophy/

**Comment by vasikgreif** [comment]
Well, this philosophy works just to some extent I think - I mean, you already have features in the plugin that are not really needed, and you just opted to include them. I think it's great to extend the plugin and add more options for the users.

**Comment by lesterchan** [comment]
Precisely, I make a mistake last time by putting in too many options. So I am not making the same mistakes. So no more options unless it is really really needed. And I find the expiry option is not needed because not many ppl ask for them. If ppl ask for them, they just have to follow in the instructions in the Readme.

Just like how WP deals with cookie and login expiry are all filters.

**Comment by vasikgreif** [comment]
OK, understood, thanks. Are you adding those filters or should I post a PR?

**Comment by lesterchan** [comment]
Put a PR, if not it will never get done if you rely on me. I am doing this as a hobby.
