### ISSUE TITLE
Release in Wordpress plugin repository

### ISSUE THREAD

**Issue by sebestenyb** [lesterchan/wp-postratings#69]
Hi

The current stable version here is 1.84, but in the Wordpress SVN is still only 1.83.1.
Can you update it there please?

Thanks for your work,

Cheers, Sebi

**Comment by lesterchan** [comment]
This is still a WIP. The WP one is always the stable one, in GH, you can treat it as the dev branch.

**Comment by sebestenyb** [comment]
Ah thanks. Just saw in the readme 1.84 as stable, and I wondered if I'm missing something.
Do you have an ETA on the release?

Thanks, Sebi

**Comment by lesterchan** [comment]
The readme is bump for the next version? Like in WP the dev version now should be 4.4.1-rc
