### ISSUE TITLE
Network Sites - Warning in Post Ratings Options

### ISSUE THREAD

**Issue by erdembey** [lesterchan/wp-postratings#72]
Hello,

I am trying to use Post Ratings in our local network site setup.
When i try to save the setting in options page the two warnings listed below appears;

Warning: Invalid argument supplied for foreach() in ....sandbox\wp-content\plugins\wp-postratings\postratings-options.php on line 48

Warning: Invalid argument supplied for foreach() in ....sandbox\wp-content\plugins\wp-postratings\postratings-options.php on line 53

Also i am still trying to activate the plugin but it only shows (No Ratings Yet) message without an image or form

**Comment by erdembey** [comment]
This problem occurs until setting the Max Ratings value and providing values for all individual vote text.

**Comment by lesterchan** [comment]
Thanks. I fixed the error https://github.com/lesterchan/wp-postratings/commit/9dee8d1342b1bc0d10a330bc7e9b5f3cc1b5e1b5 but not sure if the problem is fixed. 
Are the fields empty when you submit them?

1. Download the dev version https://github.com/lesterchan/wp-postratings/archive/master.zip
2. Delete all files and folders in /wp-content/plugins/wp-postratings
3. Put the content in master.zip in /wp-content/plugins/wp-postratings

**Comment by erdembey** [comment]
I am sorry for the huge delay :)

Anyway, it seems right now working in my network.
But there are several strange logs in my server;

Table 'myprefix_wordpress.myprefix_2_ratings' doesn't exist

When i check my table list ratings tables are not exist in any of the network sites.
I tried to enable via network enable and individual site plugin page ...

**Comment by lesterchan** [comment]
That is weird, individual site should work.

Are you able to do some debugging on your end?

Like on this line https://github.com/lesterchan/wp-postratings/blob/master/includes/postratings-activation.php#L56, add a ```error_log( 'Create Ratings Table' )``` to see if the code even executes until there?

**Comment by erdembey** [comment]
Let me clarify ...

I am using ratings plugin in my network blogs setup.
I've both tried network activate and individual activate.
But no luck, also the code provided didn't come up in any interafece (apache log or during activation)

I've also tried moving

`global $wpdb;
$wpdb->ratings = $wpdb->prefix.'ratings';`

befure require_one directives.

**Comment by lesterchan** [comment]
I think I might know why, can you move ```register_activation_hook( __FILE__, 'ratings_activation' );``` from the postratings-activation.php to the main file wp-postratings.php after the bunch of includes? I think that might be the reason.

The plugin is undergoing some reorg of files so this bug might have appeared.

**Comment by erdembey** [comment]
Allright that solved the database creation problem.
Error logs disappeared right now. i will be looking for related logs/problems, in case i can find any, i will be sharing with you
