### ISSUE TITLE
Ability to edit the rate when Logged by username enabled

### ISSUE THREAD

**Issue by micheelengronne** [lesterchan/wp-postratings#77]
Hello,

Currently when you enable "Logged by username", people can only vote once and are unable to edit it.

People can modify their appreciation so their rate.

The other possibility is to disable "Logged by username" but it creates fake rating that way as a user can rate as many time as he wants and it increments the count.

Is it possible to add an edit own rate option ?

**Comment by lesterchan** [comment]
Nope. There is no way you can edit your own rating. The plugin is not designed to support that.

**Comment by micheelengronne** [comment]
I forked the repo and added the possibilty: https://github.com/Coppint/wp-postratings/commit/657a8b0373ef468a978dea7cf9b457c3586d65f1
