### ISSUE TITLE
How get AggregateRating meta for custom Google Rich Snippets

### ISSUE THREAD

**Issue by szakee** [lesterchan/wp-postratings#80]
Can you please  tell me how can I get the ratingCount, bestRating and ratingValue for a custom Google Rich Snippets?

Thank you

**Comment by lesterchan** [comment]
The code is calculated from https://github.com/lesterchan/wp-postratings/blob/master/wp-postratings.php#L1203-L1208

**Comment by szakee** [comment]
Thank you
