### ISSUE TITLE
Error in custom_logo

### ISSUE THREAD

**Issue by dillix** [lesterchan/wp-postratings#85]
Hi!
After update to GitHub version I got error:
`Notice: Undefined index: size in /var/www/propechen/data/www/propechen.com/wp-content/plugins/wp-postratings/wp-postratings.php on line 1184`

In line 1184 you use ['size']:
```
$size = get_theme_support( 'custom-logo' );
$custom_logo = wp_get_attachment_image_src( $custom_logo_id, $size[0]['size'] );
```

But in WP API function add_theme_support() i didn't find size index:
```
case 'custom-logo':
            if ( ! is_array( $args ) ) {
                $args = array( 0 => array() );
            }
            $defaults = array(
                'width'       => null,
                'height'      => null,
                'flex-width'  => false,
                'flex-height' => false,
                'header-text' => '',
            );
            $args[0] = wp_parse_args( array_intersect_key( $args[0], $defaults ), $defaults );
 
            // Allow full flexibility if no size is specified.
            if ( is_null( $args[0]['width'] ) && is_null( $args[0]['height'] ) ) {
                $args[0]['flex-width']  = true;
                $args[0]['flex-height'] = true;
            }
            break;
```

**Comment by lesterchan** [comment]
Damn looks like they change it, size was there when it was in Jetpack, saw the note

https://make.wordpress.org/core/2016/03/10/custom-logo/

If you change ```$custom_logo = wp_get_attachment_image_src( $custom_logo_id, $size[0]['size'] );``` to ```$custom_logo = wp_get_attachment_image_src( $custom_logo_id, 'full' );``` should work. Let me know, then I can fix it on my end.

**Comment by dillix** [comment]
Yes, it works!
