### ISSUE TITLE
Add support for non image stars

### ISSUE THREAD

**Issue by dillix** [lesterchan/wp-postratings#86]
Hi, 

Thanks for the great plugin!

Can you add support to templates for non image stars? There is good stars in free Fontawesome font: http://joxi.ru/gmv3B8pIx5Q7B2

All we need is to define:
<i class="fa fa-star-o"></i>
<i class="fa fa-star"></i>
<i class="fa fa-star-half-o"></i>
in templates.

Fontawesome font installed in many Bootstrap 3/4 themes, so capability with it would be great!

**Comment by lesterchan** [comment]
Sorry that is possible because that is not how the plugin is designed. The plugin will have to be re-written for it.

**Comment by xtrinch** [comment]
@lesterchan Would it really, though? All you really need is to enclose the img tags in a div, give them a class of on/off, and then it's really easy to hide the images and add pseudo elements with :before or :after containing a star HTML character.
