### ISSUE TITLE
Guideline on rating custom taxonomies

### ISSUE THREAD

**Issue by vinhquy** [lesterchan/wp-postratings#87]
Hi lesterchan,

Thank you for creating a great plugin. 

I have searched internet for weeks but could not find a solution related to my issue. So would you mind to give me some guideline?

At the moment, I need to create rating system for custom taxonomies in wordpress. I still can use your plugin and able to add the code to custom taxonomies. The rating is shown and work. However, there is no structured data (i.e aggregateRating, ratingvalue...) for custom taxonomies.

Could you please give me a guideline (overall steps) that I can solve this problem.

Thank you.

**Comment by lesterchan** [comment]
As the name of the plugin, it is designed for post ratings and not taxonomies rating. I am afraid I can't help you.

If it helps, here are the lines that the plugin uses to determine the  structured data https://github.com/lesterchan/wp-postratings/blob/master/wp-postratings.php#L1161-L1214
