### ISSUE TITLE
Google Structured Data - some specifications are missing

### ISSUE THREAD

**Issue by ESYdesignmarketing** [lesterchan/wp-postratings#89]
Hey there,

after testing with google structured data we are getting some errors:

image A value for the image field is required. 
publisher A value for the publisher field is required.
The review has no reviewed item specified.

Below you find URL and code. Please check. Thanks a lot for your support.

[https://search.google.com/structured-data/testing-tool?hl=en#url=https%3A%2F%2Fwww.kreativschulung.de%2Findesign-schulung](url)

`<span id="post-ratings-2858" class="post-ratings" itemscope itemtype="http://schema.org/Article" data-nonce="fad38dd774"><img id="rating_2858_1" src="https://www.kreativschulung.de/wp-content/plugins/wp-postratings/images/stars_flat(png)/rating_on.png" alt="1 Stern" title="1 Stern" onmouseover="current_rating(2858, 1, '1 Stern');" onmouseout="ratings_off(4.7, 5, 0);" onclick="rate_post();" onkeypress="rate_post();" style="cursor: pointer; border: 0px;" /><img id="rating_2858_2" src="https://www.kreativschulung.de/wp-content/plugins/wp-postratings/images/stars_flat(png)/rating_on.png" alt="2 Sterne" title="2 Sterne" onmouseover="current_rating(2858, 2, '2 Sterne');" onmouseout="ratings_off(4.7, 5, 0);" onclick="rate_post();" onkeypress="rate_post();" style="cursor: pointer; border: 0px;" /><img id="rating_2858_3" src="https://www.kreativschulung.de/wp-content/plugins/wp-postratings/images/stars_flat(png)/rating_on.png" alt="3 Sterne" title="3 Sterne" onmouseover="current_rating(2858, 3, '3 Sterne');" onmouseout="ratings_off(4.7, 5, 0);" onclick="rate_post();" onkeypress="rate_post();" style="cursor: pointer; border: 0px;" /><img id="rating_2858_4" src="https://www.kreativschulung.de/wp-content/plugins/wp-postratings/images/stars_flat(png)/rating_on.png" alt="4 Sterne" title="4 Sterne" onmouseover="current_rating(2858, 4, '4 Sterne');" onmouseout="ratings_off(4.7, 5, 0);" onclick="rate_post();" onkeypress="rate_post();" style="cursor: pointer; border: 0px;" /><img id="rating_2858_5" src="https://www.kreativschulung.de/wp-content/plugins/wp-postratings/images/stars_flat(png)/rating_half.png" alt="5 Sterne" title="5 Sterne" onmouseover="current_rating(2858, 5, '5 Sterne');" onmouseout="ratings_off(4.7, 5, 0);" onclick="rate_post();" onkeypress="rate_post();" style="cursor: pointer; border: 0px;" /> (<strong>146</strong> Bewertungen, Durchschnitt: <strong>4,66</strong> von 5)<br /><span class="post-ratings-text" id="ratings_2858_text"></span><meta itemprop="headline" content="InDesign Seminar" /><meta itemprop="description" content="" /><meta itemprop="datePublished" content="2014-05-05T14:07:50+00:00" /><meta itemprop="dateModified" content="2016-08-10T11:46:09+00:00" /><meta itemprop="url" content="https://www.kreativschulung.de/indesign-schulung" /><meta itemprop="author" content="Fabian Scholz" /><meta itemprop="mainEntityOfPage" content="https://www.kreativschulung.de/indesign-schulung" />`

**Comment by lesterchan** [comment]
It might be a theme issue on your end, can you try on the default theme without any other plugins to  to see if it works? Because it is working fine on my end https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Flesterchan.net%2Fwordpress_dev%2F2016%2F02%2F19%2Ftest-title%2F

If you are just getting a logo error, you need to do this.

`
<?php add_filter( 'wp_postratings_site_logo', 'wp_postratings_site_logo' );
function wp_postratings_site_logo( $url ) { return 'http://placehold.it/350/150.png'; } ?> 
`

**Comment by ESYdesignmarketing** [comment]
Thanks for your support. On which php file do we have to put the code snippet?
Besides image, publisher is also missing in google strutured data.
Thanks a lot

**Comment by lesterchan** [comment]
functions.php. If you are not technical, I can't really help much as my gut feel, it has something to do with your them instead.

https://github.com/lesterchan/wp-postratings/blob/master/wp-postratings.php#L1197-L1202

Publisher is gotten from your site name
